import NextIntProvider from "@/components/next-int-provider";
import Footer from "@/components/shared/footer";
import Navbar from "@/components/shared/navbar";
import type { Metadata } from "next";
import { Cairo, Inter } from "next/font/google";
import "./globals.css";
import { Suspense } from "react";
export const experimental_ppr = true;
const inter = Inter({
  subsets: ["latin"],
});

const cairo = Cairo({
  subsets: ["arabic"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // lang={locale} dir={dirHelper(locale)}
  return (
    <html>
      <body
      // className={`${
      //   {
      //     en: inter.className,
      //     ar: cairo.className,
      //   }[locale]
      // } antialiased`}
      >
        <Suspense fallback={<div>Loading...</div>}>
          <NextIntProvider>
            <Navbar />
            {children}
            <Footer />
          </NextIntProvider>
        </Suspense>
      </body>
    </html>
  );
}
