import { Toaster } from "@/components/ui/sonner";
import { dirHelper } from "@/lib/utils";
import { StackProvider } from "@stackframe/stack";
import type { Metadata } from "next";
import { NextIntlClientProvider, useLocale } from "next-intl";
import { Cairo, Inter } from "next/font/google";
import "react-phone-number-input/style.css";
import { stackServerApp } from "../stack";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
});

const cairo = Cairo({
  subsets: ["arabic"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = useLocale();

  return (
    <html lang={locale} dir={dirHelper(locale)}>
      <body
        className={`${
          {
            en: inter.className,
            ar: cairo.className,
          }[locale]
        } antialiased`}
      >
        <StackProvider app={stackServerApp}>
          <NextIntlClientProvider>
            {children}
            <Toaster richColors />
          </NextIntlClientProvider>
        </StackProvider>
      </body>
    </html>
  );
}
